run:
  deadline: 2m
  allow-parallel-runners: true

linters-settings:
  lll:
    line-length: 80
    tab-width: 4
  gocyclo:
    min-complexity: 10
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - io/ioutil
      - github.com/aws/aws-sdk-go/*
      - github.com/satori/go.uuid
      - github.com/satori/uuid
  grouper:
    const-require-single-const: true
    import-require-single-import: true

linters:
  enable-all: true
  disable:
    - varnamelen
    - ifshort
    - exhaustivestruct
    - exhaustruct
    - gofumpt
    - gci
    - funlen
    - gochecknoglobals
    - gomnd
    - nosnakecase
    - golint
    - deadcode
    - varcheck
    - structcheck
    - maligned
    - interfacer
    - scopelint
  fast: false
