version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - errchkjson
    - exhaustive
    - exhaustruct
    - funlen
    - godox
    - ireturn
    - mnd
    - nakedret
    - testpackage
    - varnamelen
  settings:
    decorder:
      dec-order:
        - const
        - var
        - type
        - func
      disable-dec-order-check: false
      disable-init-func-first-check: false
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    gocyclo:
      min-complexity: 10
    gosec:
      excludes:
        - G104
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    interfacebloat:
      max: 6
    lll:
      line-length: 80
      tab-width: 4
    makezero:
      always: true
    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: argument-limit
          arguments:
            - 5
        - name: comment-spacings
          arguments:
            - nolint
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: function-result-limit
          arguments:
            - 4
        - name: max-public-structs
          arguments:
            - 5
        - name: add-constant
          disabled: true
        - name: banned-characters
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: package-comments
          disabled: true
        - name: struct-tag
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -QF1008
    tagalign:
      align: false
      order:
        - yaml
        - json
        - toml
        - mapstructure
        - binding
        - validate
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          env: upperSnake
          envconfig: upperSnake
          json: camel
          mapstructure: kebab
          xml: camel
          yaml: camel
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - httputil.Error(
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - errcheck
          - gocritic
          - maintidx
          - revive
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
