port: 8888
logLevel: 0
services:
  provider:
    dir: /path/to/graph/dir
    root:
      content: hello
      template:
        name: "{{ .RawName }}"
        weight: 0
        content: |
          # {{ .Name }}

          <rat graph depth=1 />

          ---
  urlResolver:
    fileservers:
      - authority: http://fileserver:8080
        user: username
        password: passwd
  sync:
    repoDir: /path/to/dir/containing/.git
    interval: 10s
    keyPath: /path/to/key
    keyPassword: passwd
