port: 8889
logLevel: 0
services:
  provider:
    dir: /Users/rzvejs/notes
    enablePathCache: true
    # root:
    #   content: |
    #     # Notes
    #     <rat graph depth=1 />
    #     ---
    #   template:
    #     name: "{{ .RawName }}"
    #     weight: "0"
    #     content: |
    #       # {{ .Name }}
    #
    #       <rat graph depth=1 />
    #
    #       ---
  urlResolver:
    fileservers:
      - authority: http://127.0.0.1:8080
        user: rat-client
        password: eeh8eexohGhooBeiSahTaihe1wohzoof
      - authority: http://192.168.0.103:8080
        user: rat-client
        password: eeh8eexohGhooBeiSahTaihe1wohzoof
  # sync:
  #   repoDir: /path/to/dir/containing/.git
  #   interval: 10s
  #   keyPath: /path/to/key
  #   keyPassword: passwd

  # auth:
  #   username: ruzv
  #   passwordHash: $2a$10$Yms8QUkCST6hofmeTvwrLu5Uhw1bptKd809xT94ARgKyZ4zTfPZhm
  #   tokenExpiration: 30m
  #   secret: token-creation-secret
  # indexPath: /Users/rzvejs/notesIndex
