services:
  rat:
    container_name: rat
    image: ruzv/rat:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAT_VERSION: ${RAT_VERSION}
        NODE_VERSION: 20.7.0-alpine
        GO_VERSION: 1.23.2-alpine
    ports:
      - 8888:8888
      - 8877:8877

  rat-docs:
    container_name: rat-docs
    image: ruzv/rat:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAT_VERSION: ${RAT_VERSION}
    ports:
      - 8888:8888
      - 8877:8877
    volumes:
      - ./docs:/graph
