name: checks

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: src
          version: latest

  # no need to build, unless job produces artifacts
  # build:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.20"
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #     - uses: actions/checkout@v3
  #     - name: install web dependencies
  #       working-directory: web
  #       run: |
  #         npm install
  #     - name: build
  #       run: |
  #         ./build.sh -b
