name: PIPELINE

on:
  push:
    branches: 
      - 'main'
    tags:
      - '*'
  pull_request:
    branches: 
      - 'master'

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 1.49.0
